# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Jmdfacp5O!
      POSTGRES_USER: admin
      POSTGRES_DB: boilerplate

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
